/*
Produzido por: Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
package telas;

import dao.ProdutosDAO;
import javax.swing.JOptionPane;
import model.Produtos;

/**
 *
 * @author Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
public class FrmCadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroProdutos
     */
    public FrmCadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnome = new javax.swing.JTextField();
        txtcusto = new javax.swing.JTextField();
        txtvenda = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcodbarra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menutitulo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        menucadastrar = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 325));
        setResizable(false);
        setSize(new java.awt.Dimension(425, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, 30));

        txtcusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtcusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, 30));

        txtvenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvendaActionPerformed(evt);
            }
        });
        getContentPane().add(txtvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 70, 30));

        txtdescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 280, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Custo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Valor de venda:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Descrição:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 30));

        txtcodbarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodbarraActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cod. de barras:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        menutitulo.setText("Cadastro de produtos");
        jMenuBar1.add(menutitulo);

        jMenu1.setText("                                 ");
        jMenuBar1.add(jMenu1);

        menucadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643774 - disk floppy save saveas saved saving.png"))); // NOI18N
        menucadastrar.setText("Cadastrar");
        menucadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menucadastrar);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643769 - building home house main menu start.png"))); // NOI18N
        jMenu5.setText("Menu");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendaActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void menucadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucadastrarMouseClicked
        try {
            boolean autoriza;
            double custo, venda;
            
            try {
                custo = Double.parseDouble(txtcusto.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor de custo deve ser um valor numérico");
                txtcusto.grabFocus();
                return;
            }

            try {
                venda = Double.parseDouble(txtcusto.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Valor de venda deve ser um valor numérico");
                txtvenda.grabFocus();
                return;
            }

            autoriza = txtnome.getText().length() >= 3 && txtcusto.getText().length() >= 3 && txtvenda.getText().length() >= 3 && txtcodbarra.getText().length() >= 3;

            if (!autoriza) {
                JOptionPane.showMessageDialog(null, "Todos os campos devem conter no mínimo 3 caracteres");
                return;
            } else if (custo <= 0) {
                JOptionPane.showMessageDialog(null, "Valor de custo deve ser maior que zero");
                txtcusto.grabFocus();
                return;
            } else if (venda <= 0) {
                JOptionPane.showMessageDialog(null, "Valor de venda deve ser maior que zero");
                txtvenda.grabFocus();
                return;
            }

            Produtos obj = new Produtos();

            obj.setNome(txtnome.getText());
            obj.setValorCompra(custo);
            obj.setValorVenda(Double.parseDouble(txtvenda.getText()));
            obj.setCodBarra(txtcodbarra.getText());
            obj.setDescricao(txtdescricao.getText());

            ProdutosDAO dao = new ProdutosDAO();
            dao.Cadastrar(obj);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");

            txtnome.setText(null);
            txtcusto.setText(null);
            txtvenda.setText(null);
            txtcodbarra.setText(null);
            txtdescricao.setText(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" + e);
        }
    }//GEN-LAST:event_menucadastrarMouseClicked

    private void txtcodbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodbarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodbarraActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menucadastrar;
    private javax.swing.JMenu menutitulo;
    private javax.swing.JTextField txtcodbarra;
    private javax.swing.JTextField txtcusto;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtvenda;
    // End of variables declaration//GEN-END:variables
}
