/*
Produzido por: Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
package telas;

import dao.ClientesDAO;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Clientes;

/**
 *
 * @author Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
public class FrmCadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroClientes
     */
    public FrmCadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtendereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        txtcidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcredito = new javax.swing.JTextField();
        cbuf = new javax.swing.JComboBox<>();
        ftxtcpf = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###.###.###-##");
            ftxtcpf = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jMenuBar1 = new javax.swing.JMenuBar();
        menutitulo = new javax.swing.JMenu();
        menucadastrar = new javax.swing.JMenu();
        menuprincipal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 325));
        setPreferredSize(new java.awt.Dimension(425, 325));
        setResizable(false);
        setSize(new java.awt.Dimension(425, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, 30));

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 280, 30));

        txtendereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("UF:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 30, 30));

        txtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        getContentPane().add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 30));

        txtcidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Endereço:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Crédito:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 60, 30));

        txtcredito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreditoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 30));

        cbuf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(cbuf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, 30));

        ftxtcpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(ftxtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 110, 30));

        menutitulo.setText("Cadastro de clientes                                                          ");
        jMenuBar1.add(menutitulo);

        menucadastrar.setText("Cadastrar");
        menucadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menucadastrar);

        menuprincipal.setText("Menu");
        menuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuprincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuprincipal);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    private void menucadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucadastrarMouseClicked
        try {
            int uf;
            
            Clientes obj = new Clientes();

            obj.setNome(txtnome.getText());
            obj.setCpf(Integer.parseInt(txtcpf.getText()));
            obj.setCidade(txtcidade.getText());
            obj.setEndereco(txtendereco.getText());
            obj.setCredito(Double.parseDouble(txtcredito.getText()));
            obj.setConta(0);
            
            uf = cbuf.getSelectedIndex();
            
            switch (uf){
                case 0:
                System.out.println("Selecione a UF");
                break;
                
                case 1:
                    obj.setUf("AC");
                break;
                case 2:
                    obj.setUf("AL");
                break;
                case 3:
                    obj.setUf("AP");
                break;
                case 4:
                    obj.setUf("AM");
                    break;
                case 5:
                    obj.setUf("BA");
                break;
                case 6:
                    obj.setUf("CE");
                break;
                case 7:
                    obj.setUf("DF");
                break;
                case 8:
                    obj.setUf("ES");
                break;
                case 9:
                    obj.setUf("GO");
                break;
                case 10:
                    obj.setUf("MA");
                break;
                case 11:
                    obj.setUf("MT"); 
                break;
                case 12:
                    obj.setUf("MS");
                break;
                case 13:
                    obj.setUf("MG");
                break;
                case 14:
                    obj.setUf("PA");
                break;
                case 15:
                    obj.setUf("PB");
                break;
                case 16:
                    obj.setUf("PR");
                break;
                case 17:
                    obj.setUf("PE");
                break;
                case 18:
                    obj.setUf("PI");
                break;
                case 19:
                    obj.setUf("RJ");
                break;
                case 20:
                    obj.setUf("RN");
                break;
                case 21:
                    obj.setUf("RS");
                break;
                case 22:
                    obj.setUf("RO");
                break;
                case 23:
                    obj.setUf("RR");
                break;
                case 24:
                    obj.setUf("SC");
                break;
                case 25:
                    obj.setUf("SP");
                break;
                case 26:
                    obj.setUf("SE");
                break;
                case 27:
                    obj.setUf("TO");
                break;
            }
            
            ClientesDAO dao = new ClientesDAO();
            dao.Cadastrar(obj);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            
            txtnome.setText(null);
            txtcpf.setText(null);
            txtcidade.setText(null);
            txtendereco.setText(null);
            txtcredito.setText(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menucadastrarMouseClicked

    private void menuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuprincipalMouseClicked
        this.dispose();
    }//GEN-LAST:event_menuprincipalMouseClicked

    private void txtcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbuf;
    private javax.swing.JFormattedTextField ftxtcpf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menucadastrar;
    private javax.swing.JMenu menuprincipal;
    private javax.swing.JMenu menutitulo;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtcredito;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
