/*
Produzido por: Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
package telas;

import dao.FornecedoresDAO;
import javax.swing.JOptionPane;
import model.Fornecedores;

/**
 *
 * @author Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
public class FrmCadastroFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroFornecedores
     */
    public FrmCadastroFornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        txtcnpj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtrepresentante = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menutitulo = new javax.swing.JMenu();
        menucadastrar = new javax.swing.JMenu();
        menuprincipal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(425, 325));
        setPreferredSize(new java.awt.Dimension(425, 325));
        setResizable(false);
        setSize(new java.awt.Dimension(425, 325));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Empresa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Representante:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 100, 30));

        txtempresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, 30));

        txtcnpj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CNPJ:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 40, 30));

        txtrepresentante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtrepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        menutitulo.setText("Cadastro de fornecedores                                                ");
        jMenuBar1.add(menutitulo);

        menucadastrar.setText("Cadastrar");
        menucadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menucadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menucadastrar);

        menuprincipal.setText("Menu");
        menuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuprincipalMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuprincipal);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresaActionPerformed

    private void menucadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menucadastrarMouseClicked
        try {
            Fornecedores obj = new Fornecedores();

            obj.setEmpresa(txtempresa.getText());
            obj.setRepresentante(txtrepresentante.getText());
            obj.setCnpj(Integer.parseInt(txtcnpj.getText()));

            FornecedoresDAO dao = new FornecedoresDAO();
            dao.Cadastrar(obj);
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
            
            txtempresa.setText(null);
            txtrepresentante.setText(null);
            txtcnpj.setText(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menucadastrarMouseClicked

    private void menuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuprincipalMouseClicked
        this.dispose();
    }//GEN-LAST:event_menuprincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menucadastrar;
    private javax.swing.JMenu menuprincipal;
    private javax.swing.JMenu menutitulo;
    private javax.swing.JTextField txtcnpj;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtrepresentante;
    // End of variables declaration//GEN-END:variables
}
