/*
Produzido por: Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
package telas;

import dao.ProdutosDAO;
import javax.swing.JOptionPane;
import model.Produtos;

/**
 *
 * @author Fabiana Nunes
 */
public class FrmEditaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditaProdutos
     */
    public FrmEditaProdutos() {
        initComponents();
    }
    
    void preencher(Produtos produto) {
        
        txtcodigo.setText(String.valueOf(produto.getCod_produto()));
        txtnome.setText(produto.getNome());
        txtcusto.setText(String.valueOf(produto.getValorCompra()));
        txtvenda.setText(String.valueOf(produto.getValorVenda()));
        txtcodbarra.setText(produto.getCodBarra());
        txtdescricao.setText(produto.getDescricao());
        txtquantidade.setText(String.valueOf(produto.getQuantidade()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnome = new javax.swing.JTextField();
        txtcusto = new javax.swing.JTextField();
        txtvenda = new javax.swing.JTextField();
        txtdescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtcodbarra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menutitulo = new javax.swing.JMenu();
        menuexcluir = new javax.swing.JMenu();
        menusalvar = new javax.swing.JMenu();
        menuvoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 280, 30));

        txtcusto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtcusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, 30));

        txtvenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvendaActionPerformed(evt);
            }
        });
        getContentPane().add(txtvenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, 30));

        txtdescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtdescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 280, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Custo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Valor de venda:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Descrição:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Código do produto:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, 30));

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 30));

        txtcodbarra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodbarraActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodbarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cod. de barras:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        txtquantidade.setEditable(false);
        txtquantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtquantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtquantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 60, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Quantidade:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 30));

        menutitulo.setText("Alteração e exclusão de produtos                           ");
        jMenuBar1.add(menutitulo);

        menuexcluir.setText("Excluir");
        menuexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuexcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuexcluir);

        menusalvar.setText("Salvar");
        menusalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menusalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menusalvar);

        menuvoltar.setText("Voltar");
        menuvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuvoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuvoltar);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuexcluirMouseClicked
        try {
            Produtos obj = new Produtos();
            obj.setCod_produto(Integer.parseInt(txtcodigo.getText()));

            if(false){

            } else {
                ProdutosDAO dao = new ProdutosDAO();
                dao.Excluir(obj);
                JOptionPane.showMessageDialog(null, "Registro excluido com sucesso!");

                this.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menuexcluirMouseClicked

    private void menusalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusalvarMouseClicked
        try {
            Produtos obj = new Produtos();
            
            obj.setCod_produto(Integer.parseInt(txtcodigo.getText()));
            obj.setNome(txtnome.getText());
            obj.setValorCompra(Double.parseDouble(txtcusto.getText()));
            obj.setValorVenda(Double.parseDouble(txtvenda.getText()));
            obj.setCodBarra(txtcodbarra.getText());
            obj.setDescricao(txtdescricao.getText());
            obj.setQuantidade(Integer.parseInt(txtquantidade.getText()));

            ProdutosDAO dao = new ProdutosDAO();
            dao.Alterar(obj);
            JOptionPane.showMessageDialog(null, "Registro alterado com sucesso!");

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menusalvarMouseClicked

    private void menuvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuvoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_menuvoltarMouseClicked

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendaActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtcodbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodbarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodbarraActionPerformed

    private void txtquantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuexcluir;
    private javax.swing.JMenu menusalvar;
    private javax.swing.JMenu menutitulo;
    private javax.swing.JMenu menuvoltar;
    private javax.swing.JTextField txtcodbarra;
    public javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcusto;
    private javax.swing.JTextField txtdescricao;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtquantidade;
    private javax.swing.JTextField txtvenda;
    // End of variables declaration//GEN-END:variables
}
