/*
Produzido por: Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
package telas;

import dao.FornecedoresDAO;
import javax.swing.JOptionPane;
import model.Fornecedores;

/**
 *
 * @author Gabriel Nunes de Moraes Ghirardelli & Luiz Henrique Aguiar Campos
 */
public class FrmEditaFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form FrmEditaFornecedores
     */
    public FrmEditaFornecedores() {
        initComponents();
    }
    
    void preencher(Fornecedores fornecedor) {
        txtcodigo.setText(String.valueOf(fornecedor.getCod_fornecedor()));
        txtempresa.setText(fornecedor.getEmpresa());
        txtrepresentante.setText(fornecedor.getRepresentante());
        ftxtcnpj.setText(fornecedor.getCnpj());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtrepresentante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        ftxtcnpj = new javax.swing.JFormattedTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##.###.###/####-##");
            ftxtcnpj = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jMenuBar1 = new javax.swing.JMenuBar();
        menutitulo = new javax.swing.JMenu();
        menuexcluir = new javax.swing.JMenu();
        menusalvar = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Empresa:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Representante:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 30));

        txtempresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtempresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CNPJ:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 40, 30));

        txtrepresentante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtrepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Código do fornecedor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 30));

        txtcodigo.setEditable(false);
        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 40, 30));
        getContentPane().add(ftxtcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, 30));

        menutitulo.setText("Edição de dados - fornecedores  ");
        jMenuBar1.add(menutitulo);

        menuexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643729 - bin delete garbage rubbish trash waste.png"))); // NOI18N
        menuexcluir.setText("Excluir");
        menuexcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuexcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuexcluir);

        menusalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643774 - disk floppy save saveas saved saving.png"))); // NOI18N
        menusalvar.setText("Salvar");
        menusalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menusalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menusalvar);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3643764 - back backward left reply turn.png"))); // NOI18N
        jMenu4.setText("Voltar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresaActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void menuexcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuexcluirMouseClicked
        try {
            Fornecedores obj = new Fornecedores();
            obj.setCod_fornecedor(Integer.parseInt(txtcodigo.getText()));

            if(false){

            } else {
                FornecedoresDAO dao = new FornecedoresDAO();
                dao.Excluir(obj);

                this.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menuexcluirMouseClicked

    private void menusalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusalvarMouseClicked
        try {
            boolean autoriza;
            String cnpj = ftxtcnpj.getText();
            
            cnpj = cnpj.replace(".","");
            cnpj = cnpj.replace("-","");
            cnpj = cnpj.replace("/","");
            cnpj = cnpj.replace(" ","");
            
            autoriza = txtempresa.getText().length() >= 3 && txtrepresentante.getText().length() >= 3;
            
            if (!autoriza) {
                JOptionPane.showMessageDialog(null, "Todos os campos devem conter no mínimo 3 caracteres");
                return;
            } else if (cnpj.length() != 14) {
                JOptionPane.showMessageDialog(null, "CNPJ incompleto");
                ftxtcnpj.grabFocus();
                return;
            }
            
            Fornecedores obj = new Fornecedores();

            obj.setCod_fornecedor(Integer.parseInt(txtcodigo.getText()));
            obj.setEmpresa(txtempresa.getText());
            obj.setRepresentante(txtrepresentante.getText());
            obj.setCnpj(cnpj);
            
            FornecedoresDAO dao = new FornecedoresDAO();
            dao.Alterar(obj);

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Aconteceu o erro:" +e);
        }
    }//GEN-LAST:event_menusalvarMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditaFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditaFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftxtcnpj;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuexcluir;
    private javax.swing.JMenu menusalvar;
    private javax.swing.JMenu menutitulo;
    public javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtrepresentante;
    // End of variables declaration//GEN-END:variables
}
